language: ruby
rvm:
 - 2.3.1
services:
  - postgresql
addons:
    code_climate:
        repo_token: 24694c2955bdb2b16d1059b7a86e3845b8867464c3e10e75869a9a6ade2be30b
before_script:
  - psql -c 'create database todo_list_test;' -U postgres
  - sudo apt-get install libqt4-dev libqtwebkit-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3