language: ruby
rvm:
 - 2.3.1
services:
  - postgresql
addons:
    code_climate:
        repo_token: 24694c2955bdb2b16d1059b7a86e3845b8867464c3e10e75869a9a6ade2be30b
    postgresql: "9.4"
before_install:
      - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
      - sudo apt-get update -qq
      - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
before_script:
  - psql -c 'create database todo_list_test;' -U postgres
  - sudo apt-get install libqt4-dev libqtwebkit-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make