language: ruby
sudo: required
dist: trusty
rvm:
 - 2.3.1
services:
  - postgresql
addons:
    code_climate:
        repo_token: 24694c2955bdb2b16d1059b7a86e3845b8867464c3e10e75869a9a6ade2be30b
    postgresql: "9.4"
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
before_script:
  - psql -c 'create database todo_list_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
