language: ruby
sudo: required
dist: trusty
rvm:
 - 2.3.1
services:
  - postgresql
addons:
    code_climate:
        repo_token: 24694c2955bdb2b16d1059b7a86e3845b8867464c3e10e75869a9a6ade2be30b
    postgresql: "9.4"
before_script:
  - psql -c 'create database todo_list_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make