# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0ccc6301a2881b56251309abcc5c8c936e35488c0c882e1a5409ff77b2eeb699300e617eafc31dd6726e7538eeb3324e494dd2f721fe444de83674842119560

test:
  secret_key_base: 3dd79a78848e5f273b22c3559171336ccf89f5632e16b18ab9d64568c3a6baaf68e6547f7be23b94e25d66f610f83811e6d7a187b773e37133723c2a112bb5ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
